### ISSUE TITLE
Can't access YOURLS

### ISSUE THREAD

**Issue by rhizoet** [YOURLS/charts#279]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

I've set up YOURLS with the helm chart and just added the relevant values like Domain. When the Deployment finished and I access the Website
```
Forbidden

You don't have permission to access this resource.
```

The Logs say:
```
AH01276: Cannot serve directory /var/www/html/: No matching Director Index (index.php,index.html) found, and server-generated directory index forbidden by Options directive
```

### Expectation

Install the helm chart and access the Website without issues.

### Reproduction steps

1. Install the helm chart
2. Access the URL defined in the values

### Context

values.yaml:

```YAML
image:
  debug: true

yourls:
  domain: doma.in
  username: user
  password: "password"

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: doma.in
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: true

mariadb:
  auth:
    rootPassword: "loooooongpassword"
    database: yourls_db
    username: yourls_user
    password: "password"
```
