### ISSUE TITLE
Download and initialize plugins by `initContainers`

### ISSUE THREAD

**Issue by abdennour** [YOURLS/charts#38]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

i want to manage installing plugins from the same helm chart.

### Motivation

- keeping helm chart as single source for the infra-as-code of the Yourls instances.
- keeping helm chart as single source for config-as-code
- Complying with the release engineering principles about immutable infra
- Managing plugins lifecycle from helm chart
and this is the trigger of motivation ; installing this plugin: https://github.com/peterberbec/yourls-keyword_charset_length

### Describe the solution

We can design our default values in a case if a user wants to install this chart, he will give something like this :

```yaml
plugins:
  - name: key_char_len
     url: https://raw.githubusercontent.com/peterberbec/yourls-keyword_charset_length/master/plugin.php
  - name: plugin_xyz
     url: https://something/xyz/plugin.php
```
