### ISSUE TITLE
Unable to change port in which apache listens

### ISSUE THREAD

**Issue by cstamm13** [YOURLS/charts#468]
### Self troubleshooting

- [x] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [x] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

Helm Chart version 8.0.12

### Description

Our kubernetes cluster has port 80 reserved, and therefore I've specified service.port and containerPorts.http. 
```
service:
  port: 8080

containerPorts:
  http: 8080
```
I feel it's also important to mention that I am using two ingresses here - the ingress included in the chart is being used with cloudflare, and the other ingress (with the different ports) looks like this:
```
extraDeploy:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: yourls-internal
      labels:
        app.kubernetes.io/name: yourls
        app.kubernetes.io/instance: yourls
    spec:
      ingressClassName: nginx-internal
      tls:
        - hosts:
          - my.yourls.internal.com
          secretName: yourls-dev-cloudflare-tls
      rules:
        - host: my.yourls.internal.com
          http:
            paths:
              - path: /
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: yourls
                    port:
                      number: 8080
              - path: /
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: yourls
                    port:
                      number: 443
```

With this configuration, I am able to see that the liveliness and readiness probes are requesting the proper ports, but fail. Doing a little more digging into the container, I can see that the configuration needed for apache to listen on 8080 hasn't changed. 
```
$ cat /etc/apache2/ports.conf 
...
Listen 80
...

```

If I change that to `Listen 8080` and run `apache2ctl graceful`, everything works perfectly. However, I don't see anywhere in values.yaml or the chart source which would change that port value, and doing that every time the pod restarts would be a total bummer. 

### Expected Behavior

As a user, I would expect to be able to use any allowable ports, dictated only by the whims and caprice of my manager. I would expect those ports to be captured in the configuration values `service.port` and `containerPorts.http`, and then persisted to the container 

### Steps to Reproduce

Add a custom ingress under `extraDeploy` that specifies port 8080 (the ingress pasted above is a good example)
Set `service.port` to 8080
Set `containerPorts.http` to 8080
Deploy to kubernetes
Watch in sadness
Exec into the pod and run `sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf ; apache2ctl graceful`
Watch in happiness as the service comes to life
