### ISSUE TITLE
Pod Readiness checks fail when `yourls.schema` is set to HTTPS

### ISSUE THREAD

**Issue by rjhenry** [YOURLS/charts#76]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2 (chart 4.0.4)

### Description

When `yourls.schema` is set to `https`, the pod's readiness probe changes from
```yaml
failureThreshold: 6
httpGet:
  path: /admin/install.php
  port: http
  scheme: HTTP
initialDelaySeconds: 30
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 5
```
to
```yaml
failureThreshold: 6
httpGet:
  path: /admin/install.php
  port: https
  scheme: HTTPS
initialDelaySeconds: 30
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 5
```
However, the pod never passes this check:
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3m23s                 default-scheduler  Successfully assigned gosubme/yourls-84cccbf8cd-ztppj to adevkube02
  Normal   Pulling    3m22s                 kubelet            Pulling image "docker.io/yourls:1.8.2"
  Normal   Pulled     3m8s                  kubelet            Successfully pulled image "docker.io/yourls:1.8.2" in 13.936229479s
  Normal   Created    3m7s                  kubelet            Created container yourls
  Normal   Started    3m7s                  kubelet            Started container yourls
  Warning  Unhealthy  19s (x14 over 2m29s)  kubelet            Readiness probe failed: Get "https://10.1.174.160:443/admin/install.php": dial tcp 10.1.174.160:443: connect: connection refused
  Warning  Unhealthy  13s (x6 over 63s)     kubelet            Liveness probe failed: Get "https://10.1.174.160:443/admin/install.php": dial tcp 10.1.174.160:443: connect: connection refused
  Normal   Killing    13s                   kubelet            Container yourls failed liveness probe, will be restarted
```

### Expectation

Pod readiness check expected to Just Work.

### Reproduction steps

Deploy helm release with `yourls.schema` set to `https`.

### Context

The URLs generated by YoURLs use HTTPS regardless of the value of `schema`, likely due to TLS on the ingress resource.
